import { mkdtempSync, mkdirSync, readFileSync, rmSync, utimesSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { dobeeCachedHostTypert } from './dobee-typert-cache.ts'

const roots: string[] = []

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
  vi.restoreAllMocks()
})

function fixture() {
  const root = mkdtempSync(join(tmpdir(), 'dobee-typert-cache-'))
  roots.push(root)
  const source = join(root, 'packages/core/example/src/index.ts')
  const output = join(root, 'packages/core/example/lib/typert.host.js')
  mkdirSync(join(root, 'packages/core/example/src'), { recursive: true })
  mkdirSync(join(root, 'packages/core/example/lib'), { recursive: true })
  writeFileSync(source, 'export interface Example { value: string }\n')
  const transform = vi.fn(() => ({ code: 'lowered', map: undefined }))
  const generate = vi.fn(() =>{  writeFileSync(output, 'export const descriptor = {};\n') })
  const plugin = { name: 'upstream-typert', transform, writeBundle: generate }
  vi.spyOn(console, 'log').mockImplementation(() => {})
  return {
    root, source, output, generate, transform,
    build: () =>{  dobeeCachedHostTypert(plugin, root).writeBundle({ dir: join(root, 'packages/core/example/lib') }) },
    wrap: () => dobeeCachedHostTypert(plugin, root),
  }
}

describe('dobee Host Typert cache', () => {
  it('does not reuse generation from another package selection', () => {
    const test = fixture()
    test.build()
    dobeeCachedHostTypert({ name: 'upstream', transform: test.transform, writeBundle: test.generate }, test.root, 'desktop')
      .writeBundle({ dir: join(test.root, 'packages/core/example/lib') })
    expect(test.generate).toHaveBeenCalledTimes(2)
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(3)
  })

  it('reuses identical generated bytes across plugin instances and preserves decorator lowering', () => {
    const test = fixture()
    test.build()
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(1)
    expect(test.wrap().transform('@Decorator class Example {}', 'example.ts')).toEqual({ code: 'lowered', map: undefined })
    expect(test.transform).toHaveBeenCalledOnce()
    expect(readFileSync(test.output, 'utf8')).toBe('export const descriptor = {};\n')
  })

  it('checks only once per workspace build and waits for an output directory', () => {
    const test = fixture()
    const plugin = test.wrap()
    plugin.writeBundle({})
    expect(test.generate).not.toHaveBeenCalled()
    plugin.writeBundle({ dir: join(test.root, 'packages/core/example/lib') })
    plugin.writeBundle({ dir: join(test.root, 'packages/core/other/lib') })
    expect(test.generate).toHaveBeenCalledOnce()
  })

  it('regenerates after a source change even with restored timestamps', () => {
    const test = fixture()
    test.build()
    const date = new Date(0)
    utimesSync(test.source, date, date)
    writeFileSync(test.source, 'export interface Example { value: number }\n')
    utimesSync(test.source, date, date)
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(2)
  })

  it.each(['add', 'delete'] as const)('invalidates when a source file is %s', (operation) => {
    const test = fixture()
    test.build()
    if (operation === 'add') writeFileSync(join(test.root, 'packages/core/example/src/new.ts'), 'export type Added = string\n')
    else rmSync(test.source)
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(2)
  })

  it.each(['changed', 'missing', 'extra'] as const)('regenerates %s output artifacts', (operation) => {
    const test = fixture()
    test.build()
    if (operation === 'changed') writeFileSync(test.output, 'corrupted output\n')
    else if (operation === 'missing') rmSync(test.output)
    else writeFileSync(join(test.root, 'packages/core/example/lib/typert.remote-client.js'), 'extra output\n')
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(2)
  })

  it.each(['package.json', 'tsconfig.host.json', 'pnpm-lock.yaml'])('invalidates after a %s change', (path) => {
    const test = fixture()
    writeFileSync(join(test.root, path), '{}\n')
    test.build()
    writeFileSync(join(test.root, path), '{"changed":true}\n')
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(2)
  })

  it.each(['ts', 'mts', 'cts'])('hashes installed dependency .d.%s declarations', (extension) => {
    const test = fixture()
    const dependency = join(test.root, 'node_modules/.pnpm/example@1/node_modules/example')
    mkdirSync(dependency, { recursive: true })
    writeFileSync(join(dependency, `index.d.${extension}`), 'export type Value = string\n')
    test.build()
    writeFileSync(join(dependency, `index.d.${extension}`), 'export type Value = number\n')
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(2)
  })

  it.each(['packages/core/example/src/lib', 'native/system/src'])('hashes source under %s', (path) => {
    const test = fixture()
    const directory = join(test.root, path)
    mkdirSync(directory, { recursive: true })
    writeFileSync(join(directory, 'value.ts'), 'export type Value = string\n')
    test.build()
    writeFileSync(join(directory, 'value.ts'), 'export type Value = number\n')
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(2)
  })

  it('does not invalidate on ordinary bundle output changes', () => {
    const test = fixture()
    test.build()
    writeFileSync(join(test.root, 'packages/core/example/lib/index.js'), 'rebundled output\n')
    test.build()
    expect(test.generate).toHaveBeenCalledOnce()
  })

  it('invalidates when the executed generator JavaScript changes', () => {
    const test = fixture()
    const directory = join(test.root, 'packages/typert/generator/lib/types')
    mkdirSync(directory, { recursive: true })
    writeFileSync(join(directory, 'workspace.js'), 'export const version = 1\n')
    test.build()
    writeFileSync(join(directory, 'workspace.js'), 'export const version = 2\n')
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(2)
  })

  it('rejects a malformed cache record explicitly', () => {
    const test = fixture()
    test.build()
    writeFileSync(join(test.root, '.dsh-build/dobee-typert-cache.json'), '{"version":1}\n')
    expect(test.build).toThrow('invalid record')
  })

  it('names the cache path and recovery command for invalid JSON', () => {
    const test = fixture()
    test.build()
    writeFileSync(join(test.root, '.dsh-build/dobee-typert-cache.json'), '{')
    expect(test.build).toThrow('run pnpm run clean before rebuilding')
  })

  it('does not reuse artifacts from a failed generation', () => {
    const test = fixture()
    test.build()
    writeFileSync(test.source, 'export interface Changed {}\n')
    test.generate.mockImplementationOnce(() => { throw new Error('generation failed') })
    expect(test.build).toThrow('generation failed')
    test.build()
    expect(test.generate).toHaveBeenCalledTimes(3)
  })
})
